// @flow

import * as React from 'react';
import { defineMessages, FormattedMessage as M } from 'react-intl';

import TextField from '@material-ui/core/TextField';

import SimpleDialog from '../../misc/SimpleDialog';

import { Project } from '../../../core/store/projects';
import { type RemoteProject } from './useProjectIndex';

const messages = defineMessages({
  title: {
    id: 'app.exercises.clone_exercise_dialog.title',
    description: 'Title for the exercise cloning dialog',
    defaultMessage: 'Create new project',
  },
  description: {
    id: 'app.exercises.clone_exercise_dialog.description',
    description: 'Text for the exercise cloning dialog',
    defaultMessage: 'Please enter the project name for working on exercise "{name}".',
  },
  label: {
    id: 'app.exercises.clone_exercise_dialog.new_name_label',
    description: "Label for the exercise cloning dialog's text field",
    defaultMessage: 'Project Name',
  },
});

type SimpleDialogProps = React.ElementProps<typeof SimpleDialog>;

// this type has all properties that are generated by mountSimpleDialog()
type MountedSimpleDialogProps = $Diff<
  SimpleDialogProps,
  // these are the ones that aren't
  {|
    id: $PropertyType<SimpleDialogProps, 'id'>,
  |},
>;

type CloneRemoteProjectDialogHook = {|
  show(project: RemoteProject): void,
  mountSimpleDialog(): MountedSimpleDialogProps,
|};

type Config = {|
  project: RemoteProject,
|};

export default function useCloneRemoteProjectDialog(
  onCreate: (project: RemoteProject, name: string) => boolean | Promise<boolean>,
  allProjects: Project[],
): CloneRemoteProjectDialogHook {
  const [open, setOpen] = React.useState<boolean>(false);
  const [config, setConfig] = React.useState<Config | null>(null);
  const [newProjectName, setNewProjectName] = React.useState<string>('');

  function show(project: RemoteProject) {
    setOpen(true);
    setConfig({ project });
    setNewProjectName('');
  }

  function onCancel() {
    setOpen(false);
  }

  function onChange(event) {
    const name = event.target.value;
    const nameClean = name.replace(/[^-\w#$%().,:; ]/g, '');
    setNewProjectName(nameClean);
  }

  async function onConfirm() {
    // eslint-disable-next-line no-throw-literal
    if (!open) throw 'dialog is not shown';
    // eslint-disable-next-line no-throw-literal
    if (config === null) throw 'unreachable';

    const { project } = config;

    const success = await onCreate(project, newProjectName);
    if (success) {
      setOpen(false);
    }
  }

  const valid =
    newProjectName !== '' && allProjects.every(project => project.name !== newProjectName);

  const name = config?.project.name ?? '';

  return {
    show,
    mountSimpleDialog() {
      return {
        open,
        valid,
        title: <M {...messages.title} />,
        description: <M {...messages.description} values={{ name }} />,
        actions: 'OK_CANCEL',
        onCancel,
        onConfirm,
        children: (
          <TextField
            autoFocus
            margin="dense"
            id="name"
            label={<M {...messages.label} />}
            type="text"
            value={newProjectName}
            onChange={onChange}
            error={!valid}
            fullWidth
          />
        ),
      };
    },
  };
}
