// @flow

import * as React from 'react';
import { defineMessages, FormattedMessage as M } from 'react-intl';

import SimpleDialog from '../../misc/SimpleDialog';

import { Project } from '../../../core/store/projects';

const messages = defineMessages({
  title: {
    id: 'app.projects.delete_project_dialog.title',
    description: 'Title for the project deletion dialog',
    defaultMessage: 'Confirm deletion',
  },
  description: {
    id: 'app.projects.delete_project_dialog.description',
    description: 'Text for the project deletion dialog',
    defaultMessage: 'Are you sure you want to delete project "{name}"?',
  },
});

type SimpleDialogProps = React.ElementProps<typeof SimpleDialog>;

// this type has all properties that are generated by mountSimpleDialog()
type MountedSimpleDialogProps = $Diff<
  SimpleDialogProps,
  // these are the ones that aren't
  {|
    id: $PropertyType<SimpleDialogProps, 'id'>,
  |},
>;

type DeleteProjectDialogHook = {|
  show(project: Project): void,
  mountSimpleDialog(): MountedSimpleDialogProps,
|};

type Config = {|
  project: Project,
|};

export default function useDeleteProjectDialog(
  onDelete: (Project) => boolean | Promise<boolean>,
): DeleteProjectDialogHook {
  const [open, setOpen] = React.useState<boolean>(false);
  const [config, setConfig] = React.useState<Config | null>(null);

  function show(project: Project) {
    setOpen(true);
    setConfig({ project });
  }

  function onCancel() {
    setOpen(false);
  }

  async function onConfirm() {
    // eslint-disable-next-line no-throw-literal
    if (!open) throw 'dialog is not shown';
    // eslint-disable-next-line no-throw-literal
    if (config === null) throw 'unreachable';

    const { project } = config;

    // whether the deletion succeeded or not, we want to hide the dialog.
    // Thus, ignore the result of onDelete
    await onDelete(project);

    // we don't set the project to null because that results in a display glitch:
    // the hide animation will leave the project name visible for a split second
    setOpen(false);
  }

  const name = config?.project.name ?? '';

  return {
    show,
    mountSimpleDialog() {
      return {
        open,
        valid: true,
        title: <M {...messages.title} />,
        description: <M {...messages.description} values={{ name }} />,
        actions: 'OK_autofocus_CANCEL',
        onCancel,
        onConfirm,
      };
    },
  };
}
