// flow-typed signature: b5a2ccbf86b02de523026ccb94755d06
// flow-typed version: <<STUB>>/apollo-link-error_v^1.1.13/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-error/lib/bundle.cjs' {
  declare module.exports: any;
}

declare module 'apollo-link-error/lib/bundle.esm' {
  declare module.exports: any;
}

declare module 'apollo-link-error/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-error/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-error/lib/bundle.cjs.js' {
  declare module.exports: $Exports<'apollo-link-error/lib/bundle.cjs'>;
}
declare module 'apollo-link-error/lib/bundle.esm.js' {
  declare module.exports: $Exports<'apollo-link-error/lib/bundle.esm'>;
}
declare module 'apollo-link-error/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-error/lib/bundle.umd'>;
}
declare module 'apollo-link-error/lib/index' {
  declare module.exports: $Exports<'apollo-link-error/lib'>;
}
declare module 'apollo-link-error/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-error/lib'>;
}
