// flow-typed signature: 8dde31aeb706ac7a34e295276cf3fb33
// flow-typed version: <<STUB>>/base64-js_v^1.3.1/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'base64-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'base64-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'base64-js/base64js.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'base64-js/base64js.min.js' {
  declare module.exports: $Exports<'base64-js/base64js.min'>;
}
declare module 'base64-js/index' {
  declare module.exports: $Exports<'base64-js'>;
}
declare module 'base64-js/index.js' {
  declare module.exports: $Exports<'base64-js'>;
}
