// flow-typed signature: 7b28e549a50d03da10f5cfbb100e2e14
// flow-typed version: <<STUB>>/blockly_v^2.20190722.1/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blockly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blockly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blockly/blockly-node' {
  declare module.exports: any;
}

declare module 'blockly/blockly' {
  declare module.exports: any;
}

declare module 'blockly/blockly.min' {
  declare module.exports: any;
}

declare module 'blockly/blocks' {
  declare module.exports: any;
}

declare module 'blockly/browser' {
  declare module.exports: any;
}

declare module 'blockly/core-browser' {
  declare module.exports: any;
}

declare module 'blockly/core' {
  declare module.exports: any;
}

declare module 'blockly/dart' {
  declare module.exports: any;
}

declare module 'blockly/javascript' {
  declare module.exports: any;
}

declare module 'blockly/lua' {
  declare module.exports: any;
}

declare module 'blockly/msg/ab' {
  declare module.exports: any;
}

declare module 'blockly/msg/ar' {
  declare module.exports: any;
}

declare module 'blockly/msg/az' {
  declare module.exports: any;
}

declare module 'blockly/msg/ba' {
  declare module.exports: any;
}

declare module 'blockly/msg/bcc' {
  declare module.exports: any;
}

declare module 'blockly/msg/be-tarask' {
  declare module.exports: any;
}

declare module 'blockly/msg/be' {
  declare module.exports: any;
}

declare module 'blockly/msg/bg' {
  declare module.exports: any;
}

declare module 'blockly/msg/bn' {
  declare module.exports: any;
}

declare module 'blockly/msg/br' {
  declare module.exports: any;
}

declare module 'blockly/msg/ca' {
  declare module.exports: any;
}

declare module 'blockly/msg/cs' {
  declare module.exports: any;
}

declare module 'blockly/msg/da' {
  declare module.exports: any;
}

declare module 'blockly/msg/de' {
  declare module.exports: any;
}

declare module 'blockly/msg/diq' {
  declare module.exports: any;
}

declare module 'blockly/msg/dty' {
  declare module.exports: any;
}

declare module 'blockly/msg/ee' {
  declare module.exports: any;
}

declare module 'blockly/msg/el' {
  declare module.exports: any;
}

declare module 'blockly/msg/en-gb' {
  declare module.exports: any;
}

declare module 'blockly/msg/en' {
  declare module.exports: any;
}

declare module 'blockly/msg/eo' {
  declare module.exports: any;
}

declare module 'blockly/msg/es' {
  declare module.exports: any;
}

declare module 'blockly/msg/et' {
  declare module.exports: any;
}

declare module 'blockly/msg/eu' {
  declare module.exports: any;
}

declare module 'blockly/msg/fa' {
  declare module.exports: any;
}

declare module 'blockly/msg/fi' {
  declare module.exports: any;
}

declare module 'blockly/msg/fr' {
  declare module.exports: any;
}

declare module 'blockly/msg/gl' {
  declare module.exports: any;
}

declare module 'blockly/msg/gor' {
  declare module.exports: any;
}

declare module 'blockly/msg/ha' {
  declare module.exports: any;
}

declare module 'blockly/msg/he' {
  declare module.exports: any;
}

declare module 'blockly/msg/hi' {
  declare module.exports: any;
}

declare module 'blockly/msg/hrx' {
  declare module.exports: any;
}

declare module 'blockly/msg/hu' {
  declare module.exports: any;
}

declare module 'blockly/msg/hy' {
  declare module.exports: any;
}

declare module 'blockly/msg/ia' {
  declare module.exports: any;
}

declare module 'blockly/msg/id' {
  declare module.exports: any;
}

declare module 'blockly/msg/ig' {
  declare module.exports: any;
}

declare module 'blockly/msg/is' {
  declare module.exports: any;
}

declare module 'blockly/msg/it' {
  declare module.exports: any;
}

declare module 'blockly/msg/ja' {
  declare module.exports: any;
}

declare module 'blockly/msg/kab' {
  declare module.exports: any;
}

declare module 'blockly/msg/ko' {
  declare module.exports: any;
}

declare module 'blockly/msg/lb' {
  declare module.exports: any;
}

declare module 'blockly/msg/lki' {
  declare module.exports: any;
}

declare module 'blockly/msg/lo' {
  declare module.exports: any;
}

declare module 'blockly/msg/lrc' {
  declare module.exports: any;
}

declare module 'blockly/msg/lt' {
  declare module.exports: any;
}

declare module 'blockly/msg/lv' {
  declare module.exports: any;
}

declare module 'blockly/msg/mk' {
  declare module.exports: any;
}

declare module 'blockly/msg/mnw' {
  declare module.exports: any;
}

declare module 'blockly/msg/ms' {
  declare module.exports: any;
}

declare module 'blockly/msg/nb' {
  declare module.exports: any;
}

declare module 'blockly/msg/nl' {
  declare module.exports: any;
}

declare module 'blockly/msg/oc' {
  declare module.exports: any;
}

declare module 'blockly/msg/pl' {
  declare module.exports: any;
}

declare module 'blockly/msg/pms' {
  declare module.exports: any;
}

declare module 'blockly/msg/pt-br' {
  declare module.exports: any;
}

declare module 'blockly/msg/pt' {
  declare module.exports: any;
}

declare module 'blockly/msg/ro' {
  declare module.exports: any;
}

declare module 'blockly/msg/ru' {
  declare module.exports: any;
}

declare module 'blockly/msg/sc' {
  declare module.exports: any;
}

declare module 'blockly/msg/sd' {
  declare module.exports: any;
}

declare module 'blockly/msg/shn' {
  declare module.exports: any;
}

declare module 'blockly/msg/sk' {
  declare module.exports: any;
}

declare module 'blockly/msg/skr-arab' {
  declare module.exports: any;
}

declare module 'blockly/msg/sl' {
  declare module.exports: any;
}

declare module 'blockly/msg/sq' {
  declare module.exports: any;
}

declare module 'blockly/msg/sr-latn' {
  declare module.exports: any;
}

declare module 'blockly/msg/sr' {
  declare module.exports: any;
}

declare module 'blockly/msg/sv' {
  declare module.exports: any;
}

declare module 'blockly/msg/ta' {
  declare module.exports: any;
}

declare module 'blockly/msg/tcy' {
  declare module.exports: any;
}

declare module 'blockly/msg/te' {
  declare module.exports: any;
}

declare module 'blockly/msg/th' {
  declare module.exports: any;
}

declare module 'blockly/msg/tl' {
  declare module.exports: any;
}

declare module 'blockly/msg/tlh' {
  declare module.exports: any;
}

declare module 'blockly/msg/tr' {
  declare module.exports: any;
}

declare module 'blockly/msg/ug-arab' {
  declare module.exports: any;
}

declare module 'blockly/msg/uk' {
  declare module.exports: any;
}

declare module 'blockly/msg/ur' {
  declare module.exports: any;
}

declare module 'blockly/msg/vi' {
  declare module.exports: any;
}

declare module 'blockly/msg/xmf' {
  declare module.exports: any;
}

declare module 'blockly/msg/yo' {
  declare module.exports: any;
}

declare module 'blockly/msg/zh-hans' {
  declare module.exports: any;
}

declare module 'blockly/msg/zh-hant' {
  declare module.exports: any;
}

declare module 'blockly/node' {
  declare module.exports: any;
}

declare module 'blockly/php' {
  declare module.exports: any;
}

declare module 'blockly/python' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blockly/blockly-node.js' {
  declare module.exports: $Exports<'blockly/blockly-node'>;
}
declare module 'blockly/blockly.js' {
  declare module.exports: $Exports<'blockly/blockly'>;
}
declare module 'blockly/blockly.min.js' {
  declare module.exports: $Exports<'blockly/blockly.min'>;
}
declare module 'blockly/blocks.js' {
  declare module.exports: $Exports<'blockly/blocks'>;
}
declare module 'blockly/browser.js' {
  declare module.exports: $Exports<'blockly/browser'>;
}
declare module 'blockly/core-browser.js' {
  declare module.exports: $Exports<'blockly/core-browser'>;
}
declare module 'blockly/core.js' {
  declare module.exports: $Exports<'blockly/core'>;
}
declare module 'blockly/dart.js' {
  declare module.exports: $Exports<'blockly/dart'>;
}
declare module 'blockly/index' {
  declare module.exports: $Exports<'blockly'>;
}
declare module 'blockly/index.js' {
  declare module.exports: $Exports<'blockly'>;
}
declare module 'blockly/javascript.js' {
  declare module.exports: $Exports<'blockly/javascript'>;
}
declare module 'blockly/lua.js' {
  declare module.exports: $Exports<'blockly/lua'>;
}
declare module 'blockly/msg/ab.js' {
  declare module.exports: $Exports<'blockly/msg/ab'>;
}
declare module 'blockly/msg/ar.js' {
  declare module.exports: $Exports<'blockly/msg/ar'>;
}
declare module 'blockly/msg/az.js' {
  declare module.exports: $Exports<'blockly/msg/az'>;
}
declare module 'blockly/msg/ba.js' {
  declare module.exports: $Exports<'blockly/msg/ba'>;
}
declare module 'blockly/msg/bcc.js' {
  declare module.exports: $Exports<'blockly/msg/bcc'>;
}
declare module 'blockly/msg/be-tarask.js' {
  declare module.exports: $Exports<'blockly/msg/be-tarask'>;
}
declare module 'blockly/msg/be.js' {
  declare module.exports: $Exports<'blockly/msg/be'>;
}
declare module 'blockly/msg/bg.js' {
  declare module.exports: $Exports<'blockly/msg/bg'>;
}
declare module 'blockly/msg/bn.js' {
  declare module.exports: $Exports<'blockly/msg/bn'>;
}
declare module 'blockly/msg/br.js' {
  declare module.exports: $Exports<'blockly/msg/br'>;
}
declare module 'blockly/msg/ca.js' {
  declare module.exports: $Exports<'blockly/msg/ca'>;
}
declare module 'blockly/msg/cs.js' {
  declare module.exports: $Exports<'blockly/msg/cs'>;
}
declare module 'blockly/msg/da.js' {
  declare module.exports: $Exports<'blockly/msg/da'>;
}
declare module 'blockly/msg/de.js' {
  declare module.exports: $Exports<'blockly/msg/de'>;
}
declare module 'blockly/msg/diq.js' {
  declare module.exports: $Exports<'blockly/msg/diq'>;
}
declare module 'blockly/msg/dty.js' {
  declare module.exports: $Exports<'blockly/msg/dty'>;
}
declare module 'blockly/msg/ee.js' {
  declare module.exports: $Exports<'blockly/msg/ee'>;
}
declare module 'blockly/msg/el.js' {
  declare module.exports: $Exports<'blockly/msg/el'>;
}
declare module 'blockly/msg/en-gb.js' {
  declare module.exports: $Exports<'blockly/msg/en-gb'>;
}
declare module 'blockly/msg/en.js' {
  declare module.exports: $Exports<'blockly/msg/en'>;
}
declare module 'blockly/msg/eo.js' {
  declare module.exports: $Exports<'blockly/msg/eo'>;
}
declare module 'blockly/msg/es.js' {
  declare module.exports: $Exports<'blockly/msg/es'>;
}
declare module 'blockly/msg/et.js' {
  declare module.exports: $Exports<'blockly/msg/et'>;
}
declare module 'blockly/msg/eu.js' {
  declare module.exports: $Exports<'blockly/msg/eu'>;
}
declare module 'blockly/msg/fa.js' {
  declare module.exports: $Exports<'blockly/msg/fa'>;
}
declare module 'blockly/msg/fi.js' {
  declare module.exports: $Exports<'blockly/msg/fi'>;
}
declare module 'blockly/msg/fr.js' {
  declare module.exports: $Exports<'blockly/msg/fr'>;
}
declare module 'blockly/msg/gl.js' {
  declare module.exports: $Exports<'blockly/msg/gl'>;
}
declare module 'blockly/msg/gor.js' {
  declare module.exports: $Exports<'blockly/msg/gor'>;
}
declare module 'blockly/msg/ha.js' {
  declare module.exports: $Exports<'blockly/msg/ha'>;
}
declare module 'blockly/msg/he.js' {
  declare module.exports: $Exports<'blockly/msg/he'>;
}
declare module 'blockly/msg/hi.js' {
  declare module.exports: $Exports<'blockly/msg/hi'>;
}
declare module 'blockly/msg/hrx.js' {
  declare module.exports: $Exports<'blockly/msg/hrx'>;
}
declare module 'blockly/msg/hu.js' {
  declare module.exports: $Exports<'blockly/msg/hu'>;
}
declare module 'blockly/msg/hy.js' {
  declare module.exports: $Exports<'blockly/msg/hy'>;
}
declare module 'blockly/msg/ia.js' {
  declare module.exports: $Exports<'blockly/msg/ia'>;
}
declare module 'blockly/msg/id.js' {
  declare module.exports: $Exports<'blockly/msg/id'>;
}
declare module 'blockly/msg/ig.js' {
  declare module.exports: $Exports<'blockly/msg/ig'>;
}
declare module 'blockly/msg/is.js' {
  declare module.exports: $Exports<'blockly/msg/is'>;
}
declare module 'blockly/msg/it.js' {
  declare module.exports: $Exports<'blockly/msg/it'>;
}
declare module 'blockly/msg/ja.js' {
  declare module.exports: $Exports<'blockly/msg/ja'>;
}
declare module 'blockly/msg/kab.js' {
  declare module.exports: $Exports<'blockly/msg/kab'>;
}
declare module 'blockly/msg/ko.js' {
  declare module.exports: $Exports<'blockly/msg/ko'>;
}
declare module 'blockly/msg/lb.js' {
  declare module.exports: $Exports<'blockly/msg/lb'>;
}
declare module 'blockly/msg/lki.js' {
  declare module.exports: $Exports<'blockly/msg/lki'>;
}
declare module 'blockly/msg/lo.js' {
  declare module.exports: $Exports<'blockly/msg/lo'>;
}
declare module 'blockly/msg/lrc.js' {
  declare module.exports: $Exports<'blockly/msg/lrc'>;
}
declare module 'blockly/msg/lt.js' {
  declare module.exports: $Exports<'blockly/msg/lt'>;
}
declare module 'blockly/msg/lv.js' {
  declare module.exports: $Exports<'blockly/msg/lv'>;
}
declare module 'blockly/msg/mk.js' {
  declare module.exports: $Exports<'blockly/msg/mk'>;
}
declare module 'blockly/msg/mnw.js' {
  declare module.exports: $Exports<'blockly/msg/mnw'>;
}
declare module 'blockly/msg/ms.js' {
  declare module.exports: $Exports<'blockly/msg/ms'>;
}
declare module 'blockly/msg/nb.js' {
  declare module.exports: $Exports<'blockly/msg/nb'>;
}
declare module 'blockly/msg/nl.js' {
  declare module.exports: $Exports<'blockly/msg/nl'>;
}
declare module 'blockly/msg/oc.js' {
  declare module.exports: $Exports<'blockly/msg/oc'>;
}
declare module 'blockly/msg/pl.js' {
  declare module.exports: $Exports<'blockly/msg/pl'>;
}
declare module 'blockly/msg/pms.js' {
  declare module.exports: $Exports<'blockly/msg/pms'>;
}
declare module 'blockly/msg/pt-br.js' {
  declare module.exports: $Exports<'blockly/msg/pt-br'>;
}
declare module 'blockly/msg/pt.js' {
  declare module.exports: $Exports<'blockly/msg/pt'>;
}
declare module 'blockly/msg/ro.js' {
  declare module.exports: $Exports<'blockly/msg/ro'>;
}
declare module 'blockly/msg/ru.js' {
  declare module.exports: $Exports<'blockly/msg/ru'>;
}
declare module 'blockly/msg/sc.js' {
  declare module.exports: $Exports<'blockly/msg/sc'>;
}
declare module 'blockly/msg/sd.js' {
  declare module.exports: $Exports<'blockly/msg/sd'>;
}
declare module 'blockly/msg/shn.js' {
  declare module.exports: $Exports<'blockly/msg/shn'>;
}
declare module 'blockly/msg/sk.js' {
  declare module.exports: $Exports<'blockly/msg/sk'>;
}
declare module 'blockly/msg/skr-arab.js' {
  declare module.exports: $Exports<'blockly/msg/skr-arab'>;
}
declare module 'blockly/msg/sl.js' {
  declare module.exports: $Exports<'blockly/msg/sl'>;
}
declare module 'blockly/msg/sq.js' {
  declare module.exports: $Exports<'blockly/msg/sq'>;
}
declare module 'blockly/msg/sr-latn.js' {
  declare module.exports: $Exports<'blockly/msg/sr-latn'>;
}
declare module 'blockly/msg/sr.js' {
  declare module.exports: $Exports<'blockly/msg/sr'>;
}
declare module 'blockly/msg/sv.js' {
  declare module.exports: $Exports<'blockly/msg/sv'>;
}
declare module 'blockly/msg/ta.js' {
  declare module.exports: $Exports<'blockly/msg/ta'>;
}
declare module 'blockly/msg/tcy.js' {
  declare module.exports: $Exports<'blockly/msg/tcy'>;
}
declare module 'blockly/msg/te.js' {
  declare module.exports: $Exports<'blockly/msg/te'>;
}
declare module 'blockly/msg/th.js' {
  declare module.exports: $Exports<'blockly/msg/th'>;
}
declare module 'blockly/msg/tl.js' {
  declare module.exports: $Exports<'blockly/msg/tl'>;
}
declare module 'blockly/msg/tlh.js' {
  declare module.exports: $Exports<'blockly/msg/tlh'>;
}
declare module 'blockly/msg/tr.js' {
  declare module.exports: $Exports<'blockly/msg/tr'>;
}
declare module 'blockly/msg/ug-arab.js' {
  declare module.exports: $Exports<'blockly/msg/ug-arab'>;
}
declare module 'blockly/msg/uk.js' {
  declare module.exports: $Exports<'blockly/msg/uk'>;
}
declare module 'blockly/msg/ur.js' {
  declare module.exports: $Exports<'blockly/msg/ur'>;
}
declare module 'blockly/msg/vi.js' {
  declare module.exports: $Exports<'blockly/msg/vi'>;
}
declare module 'blockly/msg/xmf.js' {
  declare module.exports: $Exports<'blockly/msg/xmf'>;
}
declare module 'blockly/msg/yo.js' {
  declare module.exports: $Exports<'blockly/msg/yo'>;
}
declare module 'blockly/msg/zh-hans.js' {
  declare module.exports: $Exports<'blockly/msg/zh-hans'>;
}
declare module 'blockly/msg/zh-hant.js' {
  declare module.exports: $Exports<'blockly/msg/zh-hant'>;
}
declare module 'blockly/node.js' {
  declare module.exports: $Exports<'blockly/node'>;
}
declare module 'blockly/php.js' {
  declare module.exports: $Exports<'blockly/php'>;
}
declare module 'blockly/python.js' {
  declare module.exports: $Exports<'blockly/python'>;
}
