// flow-typed signature: 4f153a858aefc946131bf05210c4184f
// flow-typed version: <<STUB>>/eslint-plugin-css-modules_v^2.9.1/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-css-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-css-modules/build/core/gonzales' {
  declare module.exports: any;
}

declare module 'eslint-plugin-css-modules/build/core' {
  declare module.exports: any;
}

declare module 'eslint-plugin-css-modules/build/core/traversalUtils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-css-modules/build' {
  declare module.exports: any;
}

declare module 'eslint-plugin-css-modules/build/rules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-css-modules/build/rules/no-undef-class' {
  declare module.exports: any;
}

declare module 'eslint-plugin-css-modules/build/rules/no-unused-class' {
  declare module.exports: any;
}

declare module 'eslint-plugin-css-modules/build/types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-css-modules/packages/gonzales-primitives' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-css-modules/build/core/gonzales.js' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/core/gonzales'>;
}
declare module 'eslint-plugin-css-modules/build/core/index' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/core'>;
}
declare module 'eslint-plugin-css-modules/build/core/index.js' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/core'>;
}
declare module 'eslint-plugin-css-modules/build/core/traversalUtils.js' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/core/traversalUtils'>;
}
declare module 'eslint-plugin-css-modules/build/index' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build'>;
}
declare module 'eslint-plugin-css-modules/build/index.js' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build'>;
}
declare module 'eslint-plugin-css-modules/build/rules/index' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/rules'>;
}
declare module 'eslint-plugin-css-modules/build/rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/rules'>;
}
declare module 'eslint-plugin-css-modules/build/rules/no-undef-class.js' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/rules/no-undef-class'>;
}
declare module 'eslint-plugin-css-modules/build/rules/no-unused-class.js' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/rules/no-unused-class'>;
}
declare module 'eslint-plugin-css-modules/build/types/index' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/types'>;
}
declare module 'eslint-plugin-css-modules/build/types/index.js' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/build/types'>;
}
declare module 'eslint-plugin-css-modules/packages/gonzales-primitives.js' {
  declare module.exports: $Exports<'eslint-plugin-css-modules/packages/gonzales-primitives'>;
}
