// flow-typed signature: 3baa3bf4ce687cf034d2a2367345ba0b
// flow-typed version: <<STUB>>/filer_v^1.1.2/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'filer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'filer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'filer/dist/filer' {
  declare module.exports: any;
}

declare module 'filer/dist/filer.min' {
  declare module.exports: any;
}

declare module 'filer/lib/async' {
  declare module.exports: any;
}

declare module 'filer/lib/eventemitter' {
  declare module.exports: any;
}

declare module 'filer/lib/intercom' {
  declare module.exports: any;
}

declare module 'filer/src/constants' {
  declare module.exports: any;
}

declare module 'filer/src/directory-entry' {
  declare module.exports: any;
}

declare module 'filer/src/errors' {
  declare module.exports: any;
}

declare module 'filer/src/filesystem/implementation' {
  declare module.exports: any;
}

declare module 'filer/src/filesystem/interface' {
  declare module.exports: any;
}

declare module 'filer/src/fs-watcher' {
  declare module.exports: any;
}

declare module 'filer/src' {
  declare module.exports: any;
}

declare module 'filer/src/node' {
  declare module.exports: any;
}

declare module 'filer/src/open-file-description' {
  declare module.exports: any;
}

declare module 'filer/src/open-files' {
  declare module.exports: any;
}

declare module 'filer/src/path' {
  declare module.exports: any;
}

declare module 'filer/src/providers' {
  declare module.exports: any;
}

declare module 'filer/src/providers/indexeddb' {
  declare module.exports: any;
}

declare module 'filer/src/providers/memory' {
  declare module.exports: any;
}

declare module 'filer/src/shared' {
  declare module.exports: any;
}

declare module 'filer/src/shell/environment' {
  declare module.exports: any;
}

declare module 'filer/src/shell/shell' {
  declare module.exports: any;
}

declare module 'filer/src/stats' {
  declare module.exports: any;
}

declare module 'filer/src/super-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'filer/dist/filer.js' {
  declare module.exports: $Exports<'filer/dist/filer'>;
}
declare module 'filer/dist/filer.min.js' {
  declare module.exports: $Exports<'filer/dist/filer.min'>;
}
declare module 'filer/lib/async.js' {
  declare module.exports: $Exports<'filer/lib/async'>;
}
declare module 'filer/lib/eventemitter.js' {
  declare module.exports: $Exports<'filer/lib/eventemitter'>;
}
declare module 'filer/lib/intercom.js' {
  declare module.exports: $Exports<'filer/lib/intercom'>;
}
declare module 'filer/src/constants.js' {
  declare module.exports: $Exports<'filer/src/constants'>;
}
declare module 'filer/src/directory-entry.js' {
  declare module.exports: $Exports<'filer/src/directory-entry'>;
}
declare module 'filer/src/errors.js' {
  declare module.exports: $Exports<'filer/src/errors'>;
}
declare module 'filer/src/filesystem/implementation.js' {
  declare module.exports: $Exports<'filer/src/filesystem/implementation'>;
}
declare module 'filer/src/filesystem/interface.js' {
  declare module.exports: $Exports<'filer/src/filesystem/interface'>;
}
declare module 'filer/src/fs-watcher.js' {
  declare module.exports: $Exports<'filer/src/fs-watcher'>;
}
declare module 'filer/src/index' {
  declare module.exports: $Exports<'filer/src'>;
}
declare module 'filer/src/index.js' {
  declare module.exports: $Exports<'filer/src'>;
}
declare module 'filer/src/node.js' {
  declare module.exports: $Exports<'filer/src/node'>;
}
declare module 'filer/src/open-file-description.js' {
  declare module.exports: $Exports<'filer/src/open-file-description'>;
}
declare module 'filer/src/open-files.js' {
  declare module.exports: $Exports<'filer/src/open-files'>;
}
declare module 'filer/src/path.js' {
  declare module.exports: $Exports<'filer/src/path'>;
}
declare module 'filer/src/providers/index' {
  declare module.exports: $Exports<'filer/src/providers'>;
}
declare module 'filer/src/providers/index.js' {
  declare module.exports: $Exports<'filer/src/providers'>;
}
declare module 'filer/src/providers/indexeddb.js' {
  declare module.exports: $Exports<'filer/src/providers/indexeddb'>;
}
declare module 'filer/src/providers/memory.js' {
  declare module.exports: $Exports<'filer/src/providers/memory'>;
}
declare module 'filer/src/shared.js' {
  declare module.exports: $Exports<'filer/src/shared'>;
}
declare module 'filer/src/shell/environment.js' {
  declare module.exports: $Exports<'filer/src/shell/environment'>;
}
declare module 'filer/src/shell/shell.js' {
  declare module.exports: $Exports<'filer/src/shell/shell'>;
}
declare module 'filer/src/stats.js' {
  declare module.exports: $Exports<'filer/src/stats'>;
}
declare module 'filer/src/super-node.js' {
  declare module.exports: $Exports<'filer/src/super-node'>;
}
