// flow-typed signature: c3757ef9ef2c6db5d65b57fe65fc4033
// flow-typed version: <<STUB>>/file-loader_v^4.2.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'file-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'file-loader/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'file-loader/dist/cjs.js' {
  declare module.exports: $Exports<'file-loader/dist/cjs'>;
}
declare module 'file-loader/dist/index' {
  declare module.exports: $Exports<'file-loader/dist'>;
}
declare module 'file-loader/dist/index.js' {
  declare module.exports: $Exports<'file-loader/dist'>;
}
