// flow-typed signature: c633553a0f99820e24ce2630ffdb2859
// flow-typed version: <<STUB>>/flexlayout-react_v^0.3.4/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flexlayout-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flexlayout-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flexlayout-react/dist/flexlayout_min' {
  declare module.exports: any;
}

declare module 'flexlayout-react/dist/flexlayout' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/Attribute' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/AttributeDefinitions' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/DockLocation' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/DragDrop' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/DropInfo' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/I18nLabel' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/index' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/Action' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/Actions' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/BorderNode' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/BorderSet' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/IDraggable' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/IDropTarget' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/Model' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/Node' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/RowNode' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/SplitterNode' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/TabNode' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/model/TabSetNode' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/Orientation' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/PopupMenu' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/Rect' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/Types' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/view/BorderButton' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/view/BorderTabSet' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/view/Layout' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/view/Splitter' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/view/Tab' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/view/TabButton' {
  declare module.exports: any;
}

declare module 'flexlayout-react/lib/view/TabSet' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flexlayout-react/dist/flexlayout_min.js' {
  declare module.exports: $Exports<'flexlayout-react/dist/flexlayout_min'>;
}
declare module 'flexlayout-react/dist/flexlayout.js' {
  declare module.exports: $Exports<'flexlayout-react/dist/flexlayout'>;
}
declare module 'flexlayout-react/lib/Attribute.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/Attribute'>;
}
declare module 'flexlayout-react/lib/AttributeDefinitions.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/AttributeDefinitions'>;
}
declare module 'flexlayout-react/lib/DockLocation.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/DockLocation'>;
}
declare module 'flexlayout-react/lib/DragDrop.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/DragDrop'>;
}
declare module 'flexlayout-react/lib/DropInfo.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/DropInfo'>;
}
declare module 'flexlayout-react/lib/I18nLabel.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/I18nLabel'>;
}
declare module 'flexlayout-react/lib/index.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/index'>;
}
declare module 'flexlayout-react/lib/model/Action.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/Action'>;
}
declare module 'flexlayout-react/lib/model/Actions.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/Actions'>;
}
declare module 'flexlayout-react/lib/model/BorderNode.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/BorderNode'>;
}
declare module 'flexlayout-react/lib/model/BorderSet.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/BorderSet'>;
}
declare module 'flexlayout-react/lib/model/IDraggable.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/IDraggable'>;
}
declare module 'flexlayout-react/lib/model/IDropTarget.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/IDropTarget'>;
}
declare module 'flexlayout-react/lib/model/Model.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/Model'>;
}
declare module 'flexlayout-react/lib/model/Node.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/Node'>;
}
declare module 'flexlayout-react/lib/model/RowNode.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/RowNode'>;
}
declare module 'flexlayout-react/lib/model/SplitterNode.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/SplitterNode'>;
}
declare module 'flexlayout-react/lib/model/TabNode.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/TabNode'>;
}
declare module 'flexlayout-react/lib/model/TabSetNode.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/model/TabSetNode'>;
}
declare module 'flexlayout-react/lib/Orientation.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/Orientation'>;
}
declare module 'flexlayout-react/lib/PopupMenu.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/PopupMenu'>;
}
declare module 'flexlayout-react/lib/Rect.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/Rect'>;
}
declare module 'flexlayout-react/lib/Types.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/Types'>;
}
declare module 'flexlayout-react/lib/view/BorderButton.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/view/BorderButton'>;
}
declare module 'flexlayout-react/lib/view/BorderTabSet.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/view/BorderTabSet'>;
}
declare module 'flexlayout-react/lib/view/Layout.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/view/Layout'>;
}
declare module 'flexlayout-react/lib/view/Splitter.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/view/Splitter'>;
}
declare module 'flexlayout-react/lib/view/Tab.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/view/Tab'>;
}
declare module 'flexlayout-react/lib/view/TabButton.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/view/TabButton'>;
}
declare module 'flexlayout-react/lib/view/TabSet.js' {
  declare module.exports: $Exports<'flexlayout-react/lib/view/TabSet'>;
}
