// flow-typed signature: acd58aaf7fc86dacec1a8c051f8f1cfa
// flow-typed version: <<STUB>>/graphql-tools_v^5.0.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-tools/index.cjs' {
  declare module.exports: any;
}

declare module 'graphql-tools/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-tools/index.cjs.js' {
  declare module.exports: $Exports<'graphql-tools/index.cjs'>;
}
declare module 'graphql-tools/index.esm.js' {
  declare module.exports: $Exports<'graphql-tools/index.esm'>;
}
