// flow-typed signature: cdac636338c55683077ef1b099269bbb
// flow-typed version: <<STUB>>/isomorphic-style-loader_v^4.0.0/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-style-loader/lib/index' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/lib/insertCss' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/lib/withStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-style-loader/lib/index.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/lib/index'>;
}
declare module 'isomorphic-style-loader/lib/insertCss.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/lib/insertCss'>;
}
declare module 'isomorphic-style-loader/lib/withStyles.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/lib/withStyles'>;
}
