// flow-typed signature: ba6fe5647c46733f27f884774601799e
// flow-typed version: <<STUB>>/isomorphic-style-loader_v^5.1.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-style-loader/insertCss' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/src/index' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/src/insertCss' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/src/StyleContext' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/src/useStyles' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/src/withStyles' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/StyleContext' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/useStyles' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/withStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-style-loader/index' {
  declare module.exports: $Exports<'isomorphic-style-loader'>;
}
declare module 'isomorphic-style-loader/index.js' {
  declare module.exports: $Exports<'isomorphic-style-loader'>;
}
declare module 'isomorphic-style-loader/insertCss.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/insertCss'>;
}
declare module 'isomorphic-style-loader/src/index.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/src/index'>;
}
declare module 'isomorphic-style-loader/src/insertCss.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/src/insertCss'>;
}
declare module 'isomorphic-style-loader/src/StyleContext.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/src/StyleContext'>;
}
declare module 'isomorphic-style-loader/src/useStyles.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/src/useStyles'>;
}
declare module 'isomorphic-style-loader/src/withStyles.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/src/withStyles'>;
}
declare module 'isomorphic-style-loader/StyleContext.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/StyleContext'>;
}
declare module 'isomorphic-style-loader/useStyles.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/useStyles'>;
}
declare module 'isomorphic-style-loader/withStyles.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/withStyles'>;
}
