// flow-typed signature: ff80c5094618583c16326b59a14f0756
// flow-typed version: <<STUB>>/json-dir-tree-react_v^1.0.3/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-dir-tree-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-dir-tree-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'json-dir-tree-react/index' {
  declare module.exports: $Exports<'json-dir-tree-react'>;
}
declare module 'json-dir-tree-react/index.js' {
  declare module.exports: $Exports<'json-dir-tree-react'>;
}
