// flow-typed signature: 871017693ccd64bc9e67cd7ebd695a2a
// flow-typed version: <<STUB>>/jsstore_v^3.4.2/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsstore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsstore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsstore/bin/polyfill.all' {
  declare module.exports: any;
}

declare module 'jsstore/bin/polyfill.all.min' {
  declare module.exports: any;
}

declare module 'jsstore/deployer' {
  declare module.exports: any;
}

declare module 'jsstore/dist/jsstore.commonjs2' {
  declare module.exports: any;
}

declare module 'jsstore/dist/jsstore' {
  declare module.exports: any;
}

declare module 'jsstore/dist/jsstore.min' {
  declare module.exports: any;
}

declare module 'jsstore/dist/jsstore.worker.commonjs2' {
  declare module.exports: any;
}

declare module 'jsstore/dist/jsstore.worker.ie' {
  declare module.exports: any;
}

declare module 'jsstore/dist/jsstore.worker.ie.min' {
  declare module.exports: any;
}

declare module 'jsstore/dist/jsstore.worker' {
  declare module.exports: any;
}

declare module 'jsstore/dist/jsstore.worker.min' {
  declare module.exports: any;
}

declare module 'jsstore/license' {
  declare module.exports: any;
}

declare module 'jsstore/sauce_runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsstore/bin/polyfill.all.js' {
  declare module.exports: $Exports<'jsstore/bin/polyfill.all'>;
}
declare module 'jsstore/bin/polyfill.all.min.js' {
  declare module.exports: $Exports<'jsstore/bin/polyfill.all.min'>;
}
declare module 'jsstore/deployer.js' {
  declare module.exports: $Exports<'jsstore/deployer'>;
}
declare module 'jsstore/dist/jsstore.commonjs2.js' {
  declare module.exports: $Exports<'jsstore/dist/jsstore.commonjs2'>;
}
declare module 'jsstore/dist/jsstore.js' {
  declare module.exports: $Exports<'jsstore/dist/jsstore'>;
}
declare module 'jsstore/dist/jsstore.min.js' {
  declare module.exports: $Exports<'jsstore/dist/jsstore.min'>;
}
declare module 'jsstore/dist/jsstore.worker.commonjs2.js' {
  declare module.exports: $Exports<'jsstore/dist/jsstore.worker.commonjs2'>;
}
declare module 'jsstore/dist/jsstore.worker.ie.js' {
  declare module.exports: $Exports<'jsstore/dist/jsstore.worker.ie'>;
}
declare module 'jsstore/dist/jsstore.worker.ie.min.js' {
  declare module.exports: $Exports<'jsstore/dist/jsstore.worker.ie.min'>;
}
declare module 'jsstore/dist/jsstore.worker.js' {
  declare module.exports: $Exports<'jsstore/dist/jsstore.worker'>;
}
declare module 'jsstore/dist/jsstore.worker.min.js' {
  declare module.exports: $Exports<'jsstore/dist/jsstore.worker.min'>;
}
declare module 'jsstore/license.js' {
  declare module.exports: $Exports<'jsstore/license'>;
}
declare module 'jsstore/sauce_runner.js' {
  declare module.exports: $Exports<'jsstore/sauce_runner'>;
}
