// flow-typed signature: 8c884a3927fbfb1f6977e9569ee614b4
// flow-typed version: <<STUB>>/material-ui-popup-state_v1.5.3/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-popup-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-popup-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-popup-state/core' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/es/core' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/es/hooks' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/es/HoverMenu' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/es/HoverPopover' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/es/hoverWorkaround' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/es' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/hooks' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/HoverMenu' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/HoverPopover' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/hoverWorkaround' {
  declare module.exports: any;
}

declare module 'material-ui-popup-state/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-popup-state/core.js' {
  declare module.exports: $Exports<'material-ui-popup-state/core'>;
}
declare module 'material-ui-popup-state/es/core.js' {
  declare module.exports: $Exports<'material-ui-popup-state/es/core'>;
}
declare module 'material-ui-popup-state/es/hooks.js' {
  declare module.exports: $Exports<'material-ui-popup-state/es/hooks'>;
}
declare module 'material-ui-popup-state/es/HoverMenu.js' {
  declare module.exports: $Exports<'material-ui-popup-state/es/HoverMenu'>;
}
declare module 'material-ui-popup-state/es/HoverPopover.js' {
  declare module.exports: $Exports<'material-ui-popup-state/es/HoverPopover'>;
}
declare module 'material-ui-popup-state/es/hoverWorkaround.js' {
  declare module.exports: $Exports<'material-ui-popup-state/es/hoverWorkaround'>;
}
declare module 'material-ui-popup-state/es/index' {
  declare module.exports: $Exports<'material-ui-popup-state/es'>;
}
declare module 'material-ui-popup-state/es/index.js' {
  declare module.exports: $Exports<'material-ui-popup-state/es'>;
}
declare module 'material-ui-popup-state/hooks.js' {
  declare module.exports: $Exports<'material-ui-popup-state/hooks'>;
}
declare module 'material-ui-popup-state/HoverMenu.js' {
  declare module.exports: $Exports<'material-ui-popup-state/HoverMenu'>;
}
declare module 'material-ui-popup-state/HoverPopover.js' {
  declare module.exports: $Exports<'material-ui-popup-state/HoverPopover'>;
}
declare module 'material-ui-popup-state/hoverWorkaround.js' {
  declare module.exports: $Exports<'material-ui-popup-state/hoverWorkaround'>;
}
declare module 'material-ui-popup-state/index' {
  declare module.exports: $Exports<'material-ui-popup-state'>;
}
declare module 'material-ui-popup-state/index.js' {
  declare module.exports: $Exports<'material-ui-popup-state'>;
}
declare module 'material-ui-popup-state/webpack.config.js' {
  declare module.exports: $Exports<'material-ui-popup-state/webpack.config'>;
}
