// flow-typed signature: 58faed0c7fcf032e6cc5fda4197cffbd
// flow-typed version: <<STUB>>/matter-js_v^0.14.2/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'matter-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'matter-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'matter-js/build/matter-dev' {
  declare module.exports: any;
}

declare module 'matter-js/build/matter-dev.min' {
  declare module.exports: any;
}

declare module 'matter-js/build/matter' {
  declare module.exports: any;
}

declare module 'matter-js/build/matter.min' {
  declare module.exports: any;
}

declare module 'matter-js/src/body/Body' {
  declare module.exports: any;
}

declare module 'matter-js/src/body/Composite' {
  declare module.exports: any;
}

declare module 'matter-js/src/body/World' {
  declare module.exports: any;
}

declare module 'matter-js/src/collision/Contact' {
  declare module.exports: any;
}

declare module 'matter-js/src/collision/Detector' {
  declare module.exports: any;
}

declare module 'matter-js/src/collision/Grid' {
  declare module.exports: any;
}

declare module 'matter-js/src/collision/Pair' {
  declare module.exports: any;
}

declare module 'matter-js/src/collision/Pairs' {
  declare module.exports: any;
}

declare module 'matter-js/src/collision/Query' {
  declare module.exports: any;
}

declare module 'matter-js/src/collision/Resolver' {
  declare module.exports: any;
}

declare module 'matter-js/src/collision/SAT' {
  declare module.exports: any;
}

declare module 'matter-js/src/constraint/Constraint' {
  declare module.exports: any;
}

declare module 'matter-js/src/constraint/MouseConstraint' {
  declare module.exports: any;
}

declare module 'matter-js/src/core/Common' {
  declare module.exports: any;
}

declare module 'matter-js/src/core/Engine' {
  declare module.exports: any;
}

declare module 'matter-js/src/core/Events' {
  declare module.exports: any;
}

declare module 'matter-js/src/core/Matter' {
  declare module.exports: any;
}

declare module 'matter-js/src/core/Metrics' {
  declare module.exports: any;
}

declare module 'matter-js/src/core/Mouse' {
  declare module.exports: any;
}

declare module 'matter-js/src/core/Plugin' {
  declare module.exports: any;
}

declare module 'matter-js/src/core/Runner' {
  declare module.exports: any;
}

declare module 'matter-js/src/core/Sleeping' {
  declare module.exports: any;
}

declare module 'matter-js/src/factory/Bodies' {
  declare module.exports: any;
}

declare module 'matter-js/src/factory/Composites' {
  declare module.exports: any;
}

declare module 'matter-js/src/geometry/Axes' {
  declare module.exports: any;
}

declare module 'matter-js/src/geometry/Bounds' {
  declare module.exports: any;
}

declare module 'matter-js/src/geometry/Svg' {
  declare module.exports: any;
}

declare module 'matter-js/src/geometry/Vector' {
  declare module.exports: any;
}

declare module 'matter-js/src/geometry/Vertices' {
  declare module.exports: any;
}

declare module 'matter-js/src/module/license' {
  declare module.exports: any;
}

declare module 'matter-js/src/module/main' {
  declare module.exports: any;
}

declare module 'matter-js/src/render/Render' {
  declare module.exports: any;
}

declare module 'matter-js/src/render/RenderPixi' {
  declare module.exports: any;
}

// Filename aliases
declare module 'matter-js/build/matter-dev.js' {
  declare module.exports: $Exports<'matter-js/build/matter-dev'>;
}
declare module 'matter-js/build/matter-dev.min.js' {
  declare module.exports: $Exports<'matter-js/build/matter-dev.min'>;
}
declare module 'matter-js/build/matter.js' {
  declare module.exports: $Exports<'matter-js/build/matter'>;
}
declare module 'matter-js/build/matter.min.js' {
  declare module.exports: $Exports<'matter-js/build/matter.min'>;
}
declare module 'matter-js/src/body/Body.js' {
  declare module.exports: $Exports<'matter-js/src/body/Body'>;
}
declare module 'matter-js/src/body/Composite.js' {
  declare module.exports: $Exports<'matter-js/src/body/Composite'>;
}
declare module 'matter-js/src/body/World.js' {
  declare module.exports: $Exports<'matter-js/src/body/World'>;
}
declare module 'matter-js/src/collision/Contact.js' {
  declare module.exports: $Exports<'matter-js/src/collision/Contact'>;
}
declare module 'matter-js/src/collision/Detector.js' {
  declare module.exports: $Exports<'matter-js/src/collision/Detector'>;
}
declare module 'matter-js/src/collision/Grid.js' {
  declare module.exports: $Exports<'matter-js/src/collision/Grid'>;
}
declare module 'matter-js/src/collision/Pair.js' {
  declare module.exports: $Exports<'matter-js/src/collision/Pair'>;
}
declare module 'matter-js/src/collision/Pairs.js' {
  declare module.exports: $Exports<'matter-js/src/collision/Pairs'>;
}
declare module 'matter-js/src/collision/Query.js' {
  declare module.exports: $Exports<'matter-js/src/collision/Query'>;
}
declare module 'matter-js/src/collision/Resolver.js' {
  declare module.exports: $Exports<'matter-js/src/collision/Resolver'>;
}
declare module 'matter-js/src/collision/SAT.js' {
  declare module.exports: $Exports<'matter-js/src/collision/SAT'>;
}
declare module 'matter-js/src/constraint/Constraint.js' {
  declare module.exports: $Exports<'matter-js/src/constraint/Constraint'>;
}
declare module 'matter-js/src/constraint/MouseConstraint.js' {
  declare module.exports: $Exports<'matter-js/src/constraint/MouseConstraint'>;
}
declare module 'matter-js/src/core/Common.js' {
  declare module.exports: $Exports<'matter-js/src/core/Common'>;
}
declare module 'matter-js/src/core/Engine.js' {
  declare module.exports: $Exports<'matter-js/src/core/Engine'>;
}
declare module 'matter-js/src/core/Events.js' {
  declare module.exports: $Exports<'matter-js/src/core/Events'>;
}
declare module 'matter-js/src/core/Matter.js' {
  declare module.exports: $Exports<'matter-js/src/core/Matter'>;
}
declare module 'matter-js/src/core/Metrics.js' {
  declare module.exports: $Exports<'matter-js/src/core/Metrics'>;
}
declare module 'matter-js/src/core/Mouse.js' {
  declare module.exports: $Exports<'matter-js/src/core/Mouse'>;
}
declare module 'matter-js/src/core/Plugin.js' {
  declare module.exports: $Exports<'matter-js/src/core/Plugin'>;
}
declare module 'matter-js/src/core/Runner.js' {
  declare module.exports: $Exports<'matter-js/src/core/Runner'>;
}
declare module 'matter-js/src/core/Sleeping.js' {
  declare module.exports: $Exports<'matter-js/src/core/Sleeping'>;
}
declare module 'matter-js/src/factory/Bodies.js' {
  declare module.exports: $Exports<'matter-js/src/factory/Bodies'>;
}
declare module 'matter-js/src/factory/Composites.js' {
  declare module.exports: $Exports<'matter-js/src/factory/Composites'>;
}
declare module 'matter-js/src/geometry/Axes.js' {
  declare module.exports: $Exports<'matter-js/src/geometry/Axes'>;
}
declare module 'matter-js/src/geometry/Bounds.js' {
  declare module.exports: $Exports<'matter-js/src/geometry/Bounds'>;
}
declare module 'matter-js/src/geometry/Svg.js' {
  declare module.exports: $Exports<'matter-js/src/geometry/Svg'>;
}
declare module 'matter-js/src/geometry/Vector.js' {
  declare module.exports: $Exports<'matter-js/src/geometry/Vector'>;
}
declare module 'matter-js/src/geometry/Vertices.js' {
  declare module.exports: $Exports<'matter-js/src/geometry/Vertices'>;
}
declare module 'matter-js/src/module/license.js' {
  declare module.exports: $Exports<'matter-js/src/module/license'>;
}
declare module 'matter-js/src/module/main.js' {
  declare module.exports: $Exports<'matter-js/src/module/main'>;
}
declare module 'matter-js/src/render/Render.js' {
  declare module.exports: $Exports<'matter-js/src/render/Render'>;
}
declare module 'matter-js/src/render/RenderPixi.js' {
  declare module.exports: $Exports<'matter-js/src/render/RenderPixi'>;
}
