// flow-typed signature: 66a304cfc21564af0db9e7097accffdb
// flow-typed version: <<STUB>>/normalize.css_v^8.0.0/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
