// flow-typed signature: eb1c9a5cdf43cfc18c55e1fb4a55e3cf
// flow-typed version: <<STUB>>/pathseg_v^1.2.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pathseg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pathseg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pathseg/pathseg' {
  declare module.exports: any;
}

declare module 'pathseg/tests/qunit/qunit-1.20.0' {
  declare module.exports: any;
}

declare module 'pathseg/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pathseg/pathseg.js' {
  declare module.exports: $Exports<'pathseg/pathseg'>;
}
declare module 'pathseg/tests/qunit/qunit-1.20.0.js' {
  declare module.exports: $Exports<'pathseg/tests/qunit/qunit-1.20.0'>;
}
declare module 'pathseg/tests/tests.js' {
  declare module.exports: $Exports<'pathseg/tests/tests'>;
}
