// flow-typed signature: 05849e36cae858424c5d10b95e364056
// flow-typed version: <<STUB>>/peer_v^0.5.3/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'peer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'peer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'peer/dist/src/api' {
  declare module.exports: any;
}

declare module 'peer/dist/src/api/middleware/auth' {
  declare module.exports: any;
}

declare module 'peer/dist/src/api/middleware/middleware' {
  declare module.exports: any;
}

declare module 'peer/dist/src/api/v1/calls' {
  declare module.exports: any;
}

declare module 'peer/dist/src/api/v1/public' {
  declare module.exports: any;
}

declare module 'peer/dist/src/config' {
  declare module.exports: any;
}

declare module 'peer/dist/src/enums' {
  declare module.exports: any;
}

declare module 'peer/dist/src' {
  declare module.exports: any;
}

declare module 'peer/dist/src/instance' {
  declare module.exports: any;
}

declare module 'peer/dist/src/messageHandler/handler' {
  declare module.exports: any;
}

declare module 'peer/dist/src/messageHandler/handlers/heartbeat' {
  declare module.exports: any;
}

declare module 'peer/dist/src/messageHandler/handlers' {
  declare module.exports: any;
}

declare module 'peer/dist/src/messageHandler/handlers/transmission' {
  declare module.exports: any;
}

declare module 'peer/dist/src/messageHandler/handlersRegistry' {
  declare module.exports: any;
}

declare module 'peer/dist/src/messageHandler' {
  declare module.exports: any;
}

declare module 'peer/dist/src/models/client' {
  declare module.exports: any;
}

declare module 'peer/dist/src/models/message' {
  declare module.exports: any;
}

declare module 'peer/dist/src/models/messageQueue' {
  declare module.exports: any;
}

declare module 'peer/dist/src/models/realm' {
  declare module.exports: any;
}

declare module 'peer/dist/src/services/checkBrokenConnections' {
  declare module.exports: any;
}

declare module 'peer/dist/src/services/messagesExpire' {
  declare module.exports: any;
}

declare module 'peer/dist/src/services/webSocketServer' {
  declare module.exports: any;
}

declare module 'peer/dist/src/services/webSocketServer/webSocket' {
  declare module.exports: any;
}

// Filename aliases
declare module 'peer/dist/src/api/index' {
  declare module.exports: $Exports<'peer/dist/src/api'>;
}
declare module 'peer/dist/src/api/index.js' {
  declare module.exports: $Exports<'peer/dist/src/api'>;
}
declare module 'peer/dist/src/api/middleware/auth/index' {
  declare module.exports: $Exports<'peer/dist/src/api/middleware/auth'>;
}
declare module 'peer/dist/src/api/middleware/auth/index.js' {
  declare module.exports: $Exports<'peer/dist/src/api/middleware/auth'>;
}
declare module 'peer/dist/src/api/middleware/middleware.js' {
  declare module.exports: $Exports<'peer/dist/src/api/middleware/middleware'>;
}
declare module 'peer/dist/src/api/v1/calls/index' {
  declare module.exports: $Exports<'peer/dist/src/api/v1/calls'>;
}
declare module 'peer/dist/src/api/v1/calls/index.js' {
  declare module.exports: $Exports<'peer/dist/src/api/v1/calls'>;
}
declare module 'peer/dist/src/api/v1/public/index' {
  declare module.exports: $Exports<'peer/dist/src/api/v1/public'>;
}
declare module 'peer/dist/src/api/v1/public/index.js' {
  declare module.exports: $Exports<'peer/dist/src/api/v1/public'>;
}
declare module 'peer/dist/src/config/index' {
  declare module.exports: $Exports<'peer/dist/src/config'>;
}
declare module 'peer/dist/src/config/index.js' {
  declare module.exports: $Exports<'peer/dist/src/config'>;
}
declare module 'peer/dist/src/enums.js' {
  declare module.exports: $Exports<'peer/dist/src/enums'>;
}
declare module 'peer/dist/src/index' {
  declare module.exports: $Exports<'peer/dist/src'>;
}
declare module 'peer/dist/src/index.js' {
  declare module.exports: $Exports<'peer/dist/src'>;
}
declare module 'peer/dist/src/instance.js' {
  declare module.exports: $Exports<'peer/dist/src/instance'>;
}
declare module 'peer/dist/src/messageHandler/handler.js' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler/handler'>;
}
declare module 'peer/dist/src/messageHandler/handlers/heartbeat/index' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler/handlers/heartbeat'>;
}
declare module 'peer/dist/src/messageHandler/handlers/heartbeat/index.js' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler/handlers/heartbeat'>;
}
declare module 'peer/dist/src/messageHandler/handlers/index' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler/handlers'>;
}
declare module 'peer/dist/src/messageHandler/handlers/index.js' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler/handlers'>;
}
declare module 'peer/dist/src/messageHandler/handlers/transmission/index' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler/handlers/transmission'>;
}
declare module 'peer/dist/src/messageHandler/handlers/transmission/index.js' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler/handlers/transmission'>;
}
declare module 'peer/dist/src/messageHandler/handlersRegistry.js' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler/handlersRegistry'>;
}
declare module 'peer/dist/src/messageHandler/index' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler'>;
}
declare module 'peer/dist/src/messageHandler/index.js' {
  declare module.exports: $Exports<'peer/dist/src/messageHandler'>;
}
declare module 'peer/dist/src/models/client.js' {
  declare module.exports: $Exports<'peer/dist/src/models/client'>;
}
declare module 'peer/dist/src/models/message.js' {
  declare module.exports: $Exports<'peer/dist/src/models/message'>;
}
declare module 'peer/dist/src/models/messageQueue.js' {
  declare module.exports: $Exports<'peer/dist/src/models/messageQueue'>;
}
declare module 'peer/dist/src/models/realm.js' {
  declare module.exports: $Exports<'peer/dist/src/models/realm'>;
}
declare module 'peer/dist/src/services/checkBrokenConnections/index' {
  declare module.exports: $Exports<'peer/dist/src/services/checkBrokenConnections'>;
}
declare module 'peer/dist/src/services/checkBrokenConnections/index.js' {
  declare module.exports: $Exports<'peer/dist/src/services/checkBrokenConnections'>;
}
declare module 'peer/dist/src/services/messagesExpire/index' {
  declare module.exports: $Exports<'peer/dist/src/services/messagesExpire'>;
}
declare module 'peer/dist/src/services/messagesExpire/index.js' {
  declare module.exports: $Exports<'peer/dist/src/services/messagesExpire'>;
}
declare module 'peer/dist/src/services/webSocketServer/index' {
  declare module.exports: $Exports<'peer/dist/src/services/webSocketServer'>;
}
declare module 'peer/dist/src/services/webSocketServer/index.js' {
  declare module.exports: $Exports<'peer/dist/src/services/webSocketServer'>;
}
declare module 'peer/dist/src/services/webSocketServer/webSocket.js' {
  declare module.exports: $Exports<'peer/dist/src/services/webSocketServer/webSocket'>;
}
