// flow-typed signature: 1c18b68e52f68802d75db44245e57c42
// flow-typed version: <<STUB>>/peerjs_v^1.2.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'peerjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'peerjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'peerjs/dist/peerjs' {
  declare module.exports: any;
}

declare module 'peerjs/dist/peerjs.min' {
  declare module.exports: any;
}

declare module 'peerjs/docs/build' {
  declare module.exports: any;
}

declare module 'peerjs/docs/js/docs' {
  declare module.exports: any;
}

declare module 'peerjs/docs/js/jquery.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'peerjs/dist/peerjs.js' {
  declare module.exports: $Exports<'peerjs/dist/peerjs'>;
}
declare module 'peerjs/dist/peerjs.min.js' {
  declare module.exports: $Exports<'peerjs/dist/peerjs.min'>;
}
declare module 'peerjs/docs/build.js' {
  declare module.exports: $Exports<'peerjs/docs/build'>;
}
declare module 'peerjs/docs/js/docs.js' {
  declare module.exports: $Exports<'peerjs/docs/js/docs'>;
}
declare module 'peerjs/docs/js/jquery.min.js' {
  declare module.exports: $Exports<'peerjs/docs/js/jquery.min'>;
}
