// flow-typed signature: 3e5c7732bf3ab21c570d4115546e7167
// flow-typed version: <<STUB>>/pixrem_v^4.0.1/flow_v0.88.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixrem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pixrem' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pixrem/lib/pixrem' {
  declare module.exports: any;
}

declare module 'pixrem/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pixrem/lib/pixrem.js' {
  declare module.exports: $Exports<'pixrem/lib/pixrem'>;
}
declare module 'pixrem/test/test.js' {
  declare module.exports: $Exports<'pixrem/test/test'>;
}
