// flow-typed signature: b10083d01f8decab35b4d25900c73f21
// flow-typed version: <<STUB>>/poly-decomp_v^0.3.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'poly-decomp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'poly-decomp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'poly-decomp/build/decomp' {
  declare module.exports: any;
}

declare module 'poly-decomp/build/decomp.min' {
  declare module.exports: any;
}

declare module 'poly-decomp/dat.gui' {
  declare module.exports: any;
}

declare module 'poly-decomp/Gruntfile' {
  declare module.exports: any;
}

declare module 'poly-decomp/src' {
  declare module.exports: any;
}

declare module 'poly-decomp/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'poly-decomp/build/decomp.js' {
  declare module.exports: $Exports<'poly-decomp/build/decomp'>;
}
declare module 'poly-decomp/build/decomp.min.js' {
  declare module.exports: $Exports<'poly-decomp/build/decomp.min'>;
}
declare module 'poly-decomp/dat.gui.js' {
  declare module.exports: $Exports<'poly-decomp/dat.gui'>;
}
declare module 'poly-decomp/Gruntfile.js' {
  declare module.exports: $Exports<'poly-decomp/Gruntfile'>;
}
declare module 'poly-decomp/src/index' {
  declare module.exports: $Exports<'poly-decomp/src'>;
}
declare module 'poly-decomp/src/index.js' {
  declare module.exports: $Exports<'poly-decomp/src'>;
}
declare module 'poly-decomp/test/index' {
  declare module.exports: $Exports<'poly-decomp/test'>;
}
declare module 'poly-decomp/test/index.js' {
  declare module.exports: $Exports<'poly-decomp/test'>;
}
