// flow-typed signature: 41aad10ba881f37eacbde784f28425ea
// flow-typed version: <<STUB>>/postcss-custom-selectors_v^5.1.2/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-selectors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-selectors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-custom-selectors/index.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-custom-selectors/index.cjs.js' {
  declare module.exports: $Exports<'postcss-custom-selectors/index.cjs'>;
}
