// flow-typed signature: 641b69357a99fdaef370e35a60c4b362
// flow-typed version: <<STUB>>/rc-tree_v^2.1.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-tree/dist/rc-tree' {
  declare module.exports: any;
}

declare module 'rc-tree/dist/rc-tree.min' {
  declare module.exports: any;
}

declare module 'rc-tree/es/contextTypes' {
  declare module.exports: any;
}

declare module 'rc-tree/es/index' {
  declare module.exports: any;
}

declare module 'rc-tree/es/Tree' {
  declare module.exports: any;
}

declare module 'rc-tree/es/TreeNode' {
  declare module.exports: any;
}

declare module 'rc-tree/es/util' {
  declare module.exports: any;
}

declare module 'rc-tree/lib/contextTypes' {
  declare module.exports: any;
}

declare module 'rc-tree/lib/index' {
  declare module.exports: any;
}

declare module 'rc-tree/lib/Tree' {
  declare module.exports: any;
}

declare module 'rc-tree/lib/TreeNode' {
  declare module.exports: any;
}

declare module 'rc-tree/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-tree/dist/rc-tree.js' {
  declare module.exports: $Exports<'rc-tree/dist/rc-tree'>;
}
declare module 'rc-tree/dist/rc-tree.min.js' {
  declare module.exports: $Exports<'rc-tree/dist/rc-tree.min'>;
}
declare module 'rc-tree/es/contextTypes.js' {
  declare module.exports: $Exports<'rc-tree/es/contextTypes'>;
}
declare module 'rc-tree/es/index.js' {
  declare module.exports: $Exports<'rc-tree/es/index'>;
}
declare module 'rc-tree/es/Tree.js' {
  declare module.exports: $Exports<'rc-tree/es/Tree'>;
}
declare module 'rc-tree/es/TreeNode.js' {
  declare module.exports: $Exports<'rc-tree/es/TreeNode'>;
}
declare module 'rc-tree/es/util.js' {
  declare module.exports: $Exports<'rc-tree/es/util'>;
}
declare module 'rc-tree/lib/contextTypes.js' {
  declare module.exports: $Exports<'rc-tree/lib/contextTypes'>;
}
declare module 'rc-tree/lib/index.js' {
  declare module.exports: $Exports<'rc-tree/lib/index'>;
}
declare module 'rc-tree/lib/Tree.js' {
  declare module.exports: $Exports<'rc-tree/lib/Tree'>;
}
declare module 'rc-tree/lib/TreeNode.js' {
  declare module.exports: $Exports<'rc-tree/lib/TreeNode'>;
}
declare module 'rc-tree/lib/util.js' {
  declare module.exports: $Exports<'rc-tree/lib/util'>;
}
