// flow-typed signature: a07395f6c4a3ff93e3752e22304fd40b
// flow-typed version: <<STUB>>/workbox-core_v^5.0.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-core/_private' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/assert' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/cacheNames' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/cacheWrapper' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/canConstructReadableStream' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/canConstructResponseFromBodyStream' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/DBWrapper' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/Deferred' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/deleteDatabase' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/dontWaitFor' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/executeQuotaErrorCallbacks' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/fetchWrapper' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/getFriendlyURL' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/logger' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/resultingClientExists' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/timeout' {
  declare module.exports: any;
}

declare module 'workbox-core/_private/WorkboxError' {
  declare module.exports: any;
}

declare module 'workbox-core/_version' {
  declare module.exports: any;
}

declare module 'workbox-core/build/workbox-core.dev' {
  declare module.exports: any;
}

declare module 'workbox-core/build/workbox-core.prod' {
  declare module.exports: any;
}

declare module 'workbox-core/cacheNames' {
  declare module.exports: any;
}

declare module 'workbox-core/clientsClaim' {
  declare module.exports: any;
}

declare module 'workbox-core/copyResponse' {
  declare module.exports: any;
}

declare module 'workbox-core/models/messages/messageGenerator' {
  declare module.exports: any;
}

declare module 'workbox-core/models/messages/messages' {
  declare module.exports: any;
}

declare module 'workbox-core/models/pluginEvents' {
  declare module.exports: any;
}

declare module 'workbox-core/models/quotaErrorCallbacks' {
  declare module.exports: any;
}

declare module 'workbox-core/registerQuotaErrorCallback' {
  declare module.exports: any;
}

declare module 'workbox-core/setCacheNameDetails' {
  declare module.exports: any;
}

declare module 'workbox-core/skipWaiting' {
  declare module.exports: any;
}

declare module 'workbox-core/types' {
  declare module.exports: any;
}

declare module 'workbox-core/utils/pluginUtils' {
  declare module.exports: any;
}

declare module 'workbox-core/utils/welcome' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workbox-core/_private.js' {
  declare module.exports: $Exports<'workbox-core/_private'>;
}
declare module 'workbox-core/_private/assert.js' {
  declare module.exports: $Exports<'workbox-core/_private/assert'>;
}
declare module 'workbox-core/_private/cacheNames.js' {
  declare module.exports: $Exports<'workbox-core/_private/cacheNames'>;
}
declare module 'workbox-core/_private/cacheWrapper.js' {
  declare module.exports: $Exports<'workbox-core/_private/cacheWrapper'>;
}
declare module 'workbox-core/_private/canConstructReadableStream.js' {
  declare module.exports: $Exports<'workbox-core/_private/canConstructReadableStream'>;
}
declare module 'workbox-core/_private/canConstructResponseFromBodyStream.js' {
  declare module.exports: $Exports<'workbox-core/_private/canConstructResponseFromBodyStream'>;
}
declare module 'workbox-core/_private/DBWrapper.js' {
  declare module.exports: $Exports<'workbox-core/_private/DBWrapper'>;
}
declare module 'workbox-core/_private/Deferred.js' {
  declare module.exports: $Exports<'workbox-core/_private/Deferred'>;
}
declare module 'workbox-core/_private/deleteDatabase.js' {
  declare module.exports: $Exports<'workbox-core/_private/deleteDatabase'>;
}
declare module 'workbox-core/_private/dontWaitFor.js' {
  declare module.exports: $Exports<'workbox-core/_private/dontWaitFor'>;
}
declare module 'workbox-core/_private/executeQuotaErrorCallbacks.js' {
  declare module.exports: $Exports<'workbox-core/_private/executeQuotaErrorCallbacks'>;
}
declare module 'workbox-core/_private/fetchWrapper.js' {
  declare module.exports: $Exports<'workbox-core/_private/fetchWrapper'>;
}
declare module 'workbox-core/_private/getFriendlyURL.js' {
  declare module.exports: $Exports<'workbox-core/_private/getFriendlyURL'>;
}
declare module 'workbox-core/_private/logger.js' {
  declare module.exports: $Exports<'workbox-core/_private/logger'>;
}
declare module 'workbox-core/_private/resultingClientExists.js' {
  declare module.exports: $Exports<'workbox-core/_private/resultingClientExists'>;
}
declare module 'workbox-core/_private/timeout.js' {
  declare module.exports: $Exports<'workbox-core/_private/timeout'>;
}
declare module 'workbox-core/_private/WorkboxError.js' {
  declare module.exports: $Exports<'workbox-core/_private/WorkboxError'>;
}
declare module 'workbox-core/_version.js' {
  declare module.exports: $Exports<'workbox-core/_version'>;
}
declare module 'workbox-core/build/workbox-core.dev.js' {
  declare module.exports: $Exports<'workbox-core/build/workbox-core.dev'>;
}
declare module 'workbox-core/build/workbox-core.prod.js' {
  declare module.exports: $Exports<'workbox-core/build/workbox-core.prod'>;
}
declare module 'workbox-core/cacheNames.js' {
  declare module.exports: $Exports<'workbox-core/cacheNames'>;
}
declare module 'workbox-core/clientsClaim.js' {
  declare module.exports: $Exports<'workbox-core/clientsClaim'>;
}
declare module 'workbox-core/copyResponse.js' {
  declare module.exports: $Exports<'workbox-core/copyResponse'>;
}
declare module 'workbox-core/index' {
  declare module.exports: $Exports<'workbox-core'>;
}
declare module 'workbox-core/index.js' {
  declare module.exports: $Exports<'workbox-core'>;
}
declare module 'workbox-core/models/messages/messageGenerator.js' {
  declare module.exports: $Exports<'workbox-core/models/messages/messageGenerator'>;
}
declare module 'workbox-core/models/messages/messages.js' {
  declare module.exports: $Exports<'workbox-core/models/messages/messages'>;
}
declare module 'workbox-core/models/pluginEvents.js' {
  declare module.exports: $Exports<'workbox-core/models/pluginEvents'>;
}
declare module 'workbox-core/models/quotaErrorCallbacks.js' {
  declare module.exports: $Exports<'workbox-core/models/quotaErrorCallbacks'>;
}
declare module 'workbox-core/registerQuotaErrorCallback.js' {
  declare module.exports: $Exports<'workbox-core/registerQuotaErrorCallback'>;
}
declare module 'workbox-core/setCacheNameDetails.js' {
  declare module.exports: $Exports<'workbox-core/setCacheNameDetails'>;
}
declare module 'workbox-core/skipWaiting.js' {
  declare module.exports: $Exports<'workbox-core/skipWaiting'>;
}
declare module 'workbox-core/types.js' {
  declare module.exports: $Exports<'workbox-core/types'>;
}
declare module 'workbox-core/utils/pluginUtils.js' {
  declare module.exports: $Exports<'workbox-core/utils/pluginUtils'>;
}
declare module 'workbox-core/utils/welcome.js' {
  declare module.exports: $Exports<'workbox-core/utils/welcome'>;
}
