// flow-typed signature: 2247a39383ef3453c8f8dee3f866831e
// flow-typed version: <<STUB>>/workbox-routing_v^5.0.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-routing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-routing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-routing/_types' {
  declare module.exports: any;
}

declare module 'workbox-routing/_version' {
  declare module.exports: any;
}

declare module 'workbox-routing/build/workbox-routing.dev' {
  declare module.exports: any;
}

declare module 'workbox-routing/build/workbox-routing.prod' {
  declare module.exports: any;
}

declare module 'workbox-routing/NavigationRoute' {
  declare module.exports: any;
}

declare module 'workbox-routing/RegExpRoute' {
  declare module.exports: any;
}

declare module 'workbox-routing/registerRoute' {
  declare module.exports: any;
}

declare module 'workbox-routing/Route' {
  declare module.exports: any;
}

declare module 'workbox-routing/Router' {
  declare module.exports: any;
}

declare module 'workbox-routing/setCatchHandler' {
  declare module.exports: any;
}

declare module 'workbox-routing/setDefaultHandler' {
  declare module.exports: any;
}

declare module 'workbox-routing/utils/constants' {
  declare module.exports: any;
}

declare module 'workbox-routing/utils/getOrCreateDefaultRouter' {
  declare module.exports: any;
}

declare module 'workbox-routing/utils/normalizeHandler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workbox-routing/_types.js' {
  declare module.exports: $Exports<'workbox-routing/_types'>;
}
declare module 'workbox-routing/_version.js' {
  declare module.exports: $Exports<'workbox-routing/_version'>;
}
declare module 'workbox-routing/build/workbox-routing.dev.js' {
  declare module.exports: $Exports<'workbox-routing/build/workbox-routing.dev'>;
}
declare module 'workbox-routing/build/workbox-routing.prod.js' {
  declare module.exports: $Exports<'workbox-routing/build/workbox-routing.prod'>;
}
declare module 'workbox-routing/index' {
  declare module.exports: $Exports<'workbox-routing'>;
}
declare module 'workbox-routing/index.js' {
  declare module.exports: $Exports<'workbox-routing'>;
}
declare module 'workbox-routing/NavigationRoute.js' {
  declare module.exports: $Exports<'workbox-routing/NavigationRoute'>;
}
declare module 'workbox-routing/RegExpRoute.js' {
  declare module.exports: $Exports<'workbox-routing/RegExpRoute'>;
}
declare module 'workbox-routing/registerRoute.js' {
  declare module.exports: $Exports<'workbox-routing/registerRoute'>;
}
declare module 'workbox-routing/Route.js' {
  declare module.exports: $Exports<'workbox-routing/Route'>;
}
declare module 'workbox-routing/Router.js' {
  declare module.exports: $Exports<'workbox-routing/Router'>;
}
declare module 'workbox-routing/setCatchHandler.js' {
  declare module.exports: $Exports<'workbox-routing/setCatchHandler'>;
}
declare module 'workbox-routing/setDefaultHandler.js' {
  declare module.exports: $Exports<'workbox-routing/setDefaultHandler'>;
}
declare module 'workbox-routing/utils/constants.js' {
  declare module.exports: $Exports<'workbox-routing/utils/constants'>;
}
declare module 'workbox-routing/utils/getOrCreateDefaultRouter.js' {
  declare module.exports: $Exports<'workbox-routing/utils/getOrCreateDefaultRouter'>;
}
declare module 'workbox-routing/utils/normalizeHandler.js' {
  declare module.exports: $Exports<'workbox-routing/utils/normalizeHandler'>;
}
