// flow-typed signature: 5dd57171d17ad5320139a8e17ce40456
// flow-typed version: <<STUB>>/workbox-precaching_v^5.0.0/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-precaching'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-precaching' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-precaching/_types' {
  declare module.exports: any;
}

declare module 'workbox-precaching/_version' {
  declare module.exports: any;
}

declare module 'workbox-precaching/addPlugins' {
  declare module.exports: any;
}

declare module 'workbox-precaching/addRoute' {
  declare module.exports: any;
}

declare module 'workbox-precaching/build/workbox-precaching.dev' {
  declare module.exports: any;
}

declare module 'workbox-precaching/build/workbox-precaching.prod' {
  declare module.exports: any;
}

declare module 'workbox-precaching/cleanupOutdatedCaches' {
  declare module.exports: any;
}

declare module 'workbox-precaching/createHandler' {
  declare module.exports: any;
}

declare module 'workbox-precaching/createHandlerBoundToURL' {
  declare module.exports: any;
}

declare module 'workbox-precaching/getCacheKeyForURL' {
  declare module.exports: any;
}

declare module 'workbox-precaching/matchPrecache' {
  declare module.exports: any;
}

declare module 'workbox-precaching/precache' {
  declare module.exports: any;
}

declare module 'workbox-precaching/precacheAndRoute' {
  declare module.exports: any;
}

declare module 'workbox-precaching/PrecacheController' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/addFetchListener' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/createCacheKey' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/deleteOutdatedCaches' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/generateURLVariations' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/getCacheKeyForURL' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/getOrCreatePrecacheController' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/precachePlugins' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/printCleanupDetails' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/printInstallDetails' {
  declare module.exports: any;
}

declare module 'workbox-precaching/utils/removeIgnoredSearchParams' {
  declare module.exports: any;
}

// Filename aliases
declare module 'workbox-precaching/_types.js' {
  declare module.exports: $Exports<'workbox-precaching/_types'>;
}
declare module 'workbox-precaching/_version.js' {
  declare module.exports: $Exports<'workbox-precaching/_version'>;
}
declare module 'workbox-precaching/addPlugins.js' {
  declare module.exports: $Exports<'workbox-precaching/addPlugins'>;
}
declare module 'workbox-precaching/addRoute.js' {
  declare module.exports: $Exports<'workbox-precaching/addRoute'>;
}
declare module 'workbox-precaching/build/workbox-precaching.dev.js' {
  declare module.exports: $Exports<'workbox-precaching/build/workbox-precaching.dev'>;
}
declare module 'workbox-precaching/build/workbox-precaching.prod.js' {
  declare module.exports: $Exports<'workbox-precaching/build/workbox-precaching.prod'>;
}
declare module 'workbox-precaching/cleanupOutdatedCaches.js' {
  declare module.exports: $Exports<'workbox-precaching/cleanupOutdatedCaches'>;
}
declare module 'workbox-precaching/createHandler.js' {
  declare module.exports: $Exports<'workbox-precaching/createHandler'>;
}
declare module 'workbox-precaching/createHandlerBoundToURL.js' {
  declare module.exports: $Exports<'workbox-precaching/createHandlerBoundToURL'>;
}
declare module 'workbox-precaching/getCacheKeyForURL.js' {
  declare module.exports: $Exports<'workbox-precaching/getCacheKeyForURL'>;
}
declare module 'workbox-precaching/index' {
  declare module.exports: $Exports<'workbox-precaching'>;
}
declare module 'workbox-precaching/index.js' {
  declare module.exports: $Exports<'workbox-precaching'>;
}
declare module 'workbox-precaching/matchPrecache.js' {
  declare module.exports: $Exports<'workbox-precaching/matchPrecache'>;
}
declare module 'workbox-precaching/precache.js' {
  declare module.exports: $Exports<'workbox-precaching/precache'>;
}
declare module 'workbox-precaching/precacheAndRoute.js' {
  declare module.exports: $Exports<'workbox-precaching/precacheAndRoute'>;
}
declare module 'workbox-precaching/PrecacheController.js' {
  declare module.exports: $Exports<'workbox-precaching/PrecacheController'>;
}
declare module 'workbox-precaching/utils/addFetchListener.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/addFetchListener'>;
}
declare module 'workbox-precaching/utils/createCacheKey.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/createCacheKey'>;
}
declare module 'workbox-precaching/utils/deleteOutdatedCaches.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/deleteOutdatedCaches'>;
}
declare module 'workbox-precaching/utils/generateURLVariations.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/generateURLVariations'>;
}
declare module 'workbox-precaching/utils/getCacheKeyForURL.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/getCacheKeyForURL'>;
}
declare module 'workbox-precaching/utils/getOrCreatePrecacheController.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/getOrCreatePrecacheController'>;
}
declare module 'workbox-precaching/utils/precachePlugins.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/precachePlugins'>;
}
declare module 'workbox-precaching/utils/printCleanupDetails.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/printCleanupDetails'>;
}
declare module 'workbox-precaching/utils/printInstallDetails.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/printInstallDetails'>;
}
declare module 'workbox-precaching/utils/removeIgnoredSearchParams.js' {
  declare module.exports: $Exports<'workbox-precaching/utils/removeIgnoredSearchParams'>;
}
