// @flow

import * as React from 'react';
import { defineMessages, FormattedMessage as M } from 'react-intl';

import TextField from '@material-ui/core/TextField';

import SimpleDialog from '../../misc/SimpleDialog';

import type { DirReference, FileType, FileDesc } from '.';

const messages = defineMessages({
  title: {
    id: 'app.ide.create_file_dialog.title',
    description: 'Title for the file creation dialog',
    defaultMessage: 'Create new {type, select, FILE {file} DIRECTORY {folder}}',
  },
  description: {
    id: 'app.ide.create_file_dialog.description',
    description: 'Text for the file creation dialog',
    defaultMessage:
      "Please enter the new {type, select, FILE {file's} DIRECTORY {folder's}} name.",
  },
});

type SimpleDialogProps = React.ElementProps<typeof SimpleDialog>;

// this type has all properties that are generated by mountSimpleDialog()
type MountedSimpleDialogProps = $Diff<
  SimpleDialogProps,
  // these are the ones that aren't
  {|
    id: $PropertyType<SimpleDialogProps, 'id'>,
  |},
>;

type CreateFileDialogHook = {|
  show(parentDir: DirReference, desc: FileDesc): void,
  mountSimpleDialog(): MountedSimpleDialogProps,
|};

type Config = {|
  parentDir: DirReference,
  desc: FileDesc,
|};

type FileNameState = {|
  newFileName: string,
  actualNewFileName: string,
  valid: boolean,
|};

export default function useCreateFileDialog(
  onCreate: (
    parentDir: DirReference,
    newFileName: string,
    type: FileType,
  ) => boolean | Promise<boolean>,
): CreateFileDialogHook {
  const [open, setOpen] = React.useState<boolean>(false);
  const [config, setConfig] = React.useState<Config | null>(null);
  const [fileNameState, setFileNameState] = React.useState<FileNameState>({
    newFileName: '',
    actualNewFileName: '',
    valid: false,
  });

  function show(parentDir: DirReference, desc: FileDesc) {
    setOpen(true);
    setConfig({ parentDir, desc });
    setFileNameState({
      newFileName: '',
      actualNewFileName: '',
      valid: false,
    });
  }

  function onCancel() {
    setOpen(false);
  }

  function onChange(event) {
    // eslint-disable-next-line no-throw-literal
    if (config === null) throw 'unreachable';

    const { parentDir, desc } = config;

    const name = event.target.value;
    const newFileName = name.replace(/[^-\w#$%().,:; ]/g, '');
    const actualNewFileName =
      desc.type === 'DIRECTORY'
        ? newFileName
        : newFileName.endsWith(desc.extension)
        ? newFileName
        : `${newFileName}${desc.extension}`;
    const valid =
      newFileName !== '' &&
      parentDir.file.contents.every(f => f.name !== actualNewFileName);
    setFileNameState({
      newFileName,
      actualNewFileName,
      valid,
    });
  }

  async function onConfirm() {
    // eslint-disable-next-line no-throw-literal
    if (!open) throw 'dialog is not shown';
    // eslint-disable-next-line no-throw-literal
    if (config === null) throw 'unreachable';

    const { parentDir, desc } = config;
    const { actualNewFileName } = fileNameState;

    const success = await onCreate(parentDir, actualNewFileName, desc.type);
    if (success) {
      setOpen(false);
    }
  }

  const desc = config !== null ? config.desc : { type: 'DIRECTORY' };
  const { type } = desc;
  const { newFileName, valid } = fileNameState;

  const placeholder = desc.type === 'FILE' ? `file${desc.extension}` : 'folder';

  return {
    show,
    mountSimpleDialog() {
      return {
        open,
        valid,
        title: <M {...messages.title} values={{ type }} />,
        description: <M {...messages.description} values={{ type }} />,
        actions: 'OK_CANCEL',
        onCancel,
        onConfirm,
        children: (
          <TextField
            autoFocus
            margin="dense"
            id="name"
            label={placeholder}
            type="text"
            value={newFileName}
            onChange={onChange}
            error={!valid}
            fullWidth
          />
        ),
      };
    },
  };
}
