// flow-typed signature: 8579ff4fe27dbd8d8294986db3f1ecb5
// flow-typed version: <<STUB>>/@uiw/react-md-editor_v^1.14.4/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@uiw/react-md-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@uiw/react-md-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@uiw/react-md-editor/lib/cjs/commands/bold' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/code' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/divider' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/fullscreen' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/hr' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/image' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/italic' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/link' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/list' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/preview' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/quote' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/strikeThrough' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/commands/title' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/components/DragBar' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/components/TextArea/hotkeys' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/components/TextArea' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/components/Toolbar' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/MDEditor' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/utils/getSurroundingWord' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/utils' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/utils/InsertTextAtPosition' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/cjs/utils/markdownUtils' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/bold' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/code' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/divider' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/fullscreen' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/hr' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/image' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/italic' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/link' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/list' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/preview' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/quote' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/strikeThrough' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/commands/title' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/components/DragBar' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/components/TextArea/hotkeys' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/components/TextArea' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/components/Toolbar' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/MDEditor' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/utils/getSurroundingWord' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/utils' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/utils/InsertTextAtPosition' {
  declare module.exports: any;
}

declare module '@uiw/react-md-editor/lib/esm/utils/markdownUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@uiw/react-md-editor/lib/cjs/commands/bold.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/bold'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/code.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/code'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/divider.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/divider'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/fullscreen.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/fullscreen'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/hr.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/hr'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/image.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/image'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/italic.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/italic'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/link.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/link'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/list.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/list'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/preview.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/preview'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/quote.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/quote'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/strikeThrough.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/strikeThrough'>;
}
declare module '@uiw/react-md-editor/lib/cjs/commands/title.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/commands/title'>;
}
declare module '@uiw/react-md-editor/lib/cjs/components/DragBar/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/components/DragBar'>;
}
declare module '@uiw/react-md-editor/lib/cjs/components/DragBar/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/components/DragBar'>;
}
declare module '@uiw/react-md-editor/lib/cjs/components/TextArea/hotkeys.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/components/TextArea/hotkeys'>;
}
declare module '@uiw/react-md-editor/lib/cjs/components/TextArea/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/components/TextArea'>;
}
declare module '@uiw/react-md-editor/lib/cjs/components/TextArea/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/components/TextArea'>;
}
declare module '@uiw/react-md-editor/lib/cjs/components/Toolbar/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/components/Toolbar'>;
}
declare module '@uiw/react-md-editor/lib/cjs/components/Toolbar/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/components/Toolbar'>;
}
declare module '@uiw/react-md-editor/lib/cjs/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs'>;
}
declare module '@uiw/react-md-editor/lib/cjs/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs'>;
}
declare module '@uiw/react-md-editor/lib/cjs/MDEditor.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/MDEditor'>;
}
declare module '@uiw/react-md-editor/lib/cjs/utils/getSurroundingWord.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/utils/getSurroundingWord'>;
}
declare module '@uiw/react-md-editor/lib/cjs/utils/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/utils'>;
}
declare module '@uiw/react-md-editor/lib/cjs/utils/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/utils'>;
}
declare module '@uiw/react-md-editor/lib/cjs/utils/InsertTextAtPosition.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/utils/InsertTextAtPosition'>;
}
declare module '@uiw/react-md-editor/lib/cjs/utils/markdownUtils.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/cjs/utils/markdownUtils'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/bold.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/bold'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/code.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/code'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/divider.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/divider'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/fullscreen.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/fullscreen'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/hr.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/hr'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/image.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/image'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/italic.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/italic'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/link.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/link'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/list.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/list'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/preview.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/preview'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/quote.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/quote'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/strikeThrough.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/strikeThrough'>;
}
declare module '@uiw/react-md-editor/lib/esm/commands/title.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/commands/title'>;
}
declare module '@uiw/react-md-editor/lib/esm/components/DragBar/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/components/DragBar'>;
}
declare module '@uiw/react-md-editor/lib/esm/components/DragBar/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/components/DragBar'>;
}
declare module '@uiw/react-md-editor/lib/esm/components/TextArea/hotkeys.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/components/TextArea/hotkeys'>;
}
declare module '@uiw/react-md-editor/lib/esm/components/TextArea/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/components/TextArea'>;
}
declare module '@uiw/react-md-editor/lib/esm/components/TextArea/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/components/TextArea'>;
}
declare module '@uiw/react-md-editor/lib/esm/components/Toolbar/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/components/Toolbar'>;
}
declare module '@uiw/react-md-editor/lib/esm/components/Toolbar/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/components/Toolbar'>;
}
declare module '@uiw/react-md-editor/lib/esm/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm'>;
}
declare module '@uiw/react-md-editor/lib/esm/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm'>;
}
declare module '@uiw/react-md-editor/lib/esm/MDEditor.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/MDEditor'>;
}
declare module '@uiw/react-md-editor/lib/esm/utils/getSurroundingWord.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/utils/getSurroundingWord'>;
}
declare module '@uiw/react-md-editor/lib/esm/utils/index' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/utils'>;
}
declare module '@uiw/react-md-editor/lib/esm/utils/index.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/utils'>;
}
declare module '@uiw/react-md-editor/lib/esm/utils/InsertTextAtPosition.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/utils/InsertTextAtPosition'>;
}
declare module '@uiw/react-md-editor/lib/esm/utils/markdownUtils.js' {
  declare module.exports: $Exports<'@uiw/react-md-editor/lib/esm/utils/markdownUtils'>;
}
